export interface OrderItem {
  id: string;
  name: string;
  quantity: number;
  price: number;
  total: number;
}

export interface Order {
  id: string;
  name: string;
  customerId?: string;
  amount: number;
  store: "Store 1" | "Store 2";
  slot: "Slot 1" | "Slot 2";
  status: "Pending" | "Packed" | "Out for Delivery" | "Delivered" | "Cancelled";
  time: string;
  date?: string;
  paymentMethod?: string;
  items?: OrderItem[];
}

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  avatarColor: string;
  address: string;
  city: string;
  pincode: string;
  joinedDate: string;
  defaultStore: "Store 1" | "Store 2";
  preferredSlot: "Slot 1" | "Slot 2";
  status: "Active" | "Inactive";
  loyaltyTier: "Bronze" | "Silver" | "Gold" | "Platinum";
  totalOrders: number;
  totalSpent: number;
  orderHistory: Order[];
}

export const mockEarningsData = [
  { time: "9 AM", earnings: 800 },
  { time: "10 AM", earnings: 1400 },
  { time: "11 AM", earnings: 1800 },
  { time: "12 PM", earnings: 2600 },
  { time: "1 PM", earnings: 3100 },
  { time: "2 PM", earnings: 2800 },
  { time: "3 PM", earnings: 3400 },
  { time: "4 PM", earnings: 4200 },
  { time: "5 PM", earnings: 5000 },
  { time: "6 PM", earnings: 5800 },
  { time: "7 PM", earnings: 7200 },
  { time: "8 PM", earnings: 5600 },
  { time: "9 PM", earnings: 3800 },
];

export const mockOrders: Order[] = [
  {
    id: "KM1024",
    customerId: "CUST-1001",
    name: "Priya Sharma",
    amount: 862,
    store: "Store 1",
    slot: "Slot 1",
    status: "Pending",
    time: "10:32 AM",
    date: "Today, 20 Sep 2026",
    paymentMethod: "UPI / GooglePay",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 2, price: 290, total: 580 },
      { id: "KM002", name: "Colgate Toothpaste (200 g)", quantity: 1, price: 120, total: 120 },
      { id: "KM006", name: "Maggi 2 Min Noodles (70 g)", quantity: 2, price: 70, total: 140 },
    ],
  },
  {
    id: "KM1023",
    customerId: "CUST-1002",
    name: "Rahul Verma",
    amount: 1420,
    store: "Store 2",
    slot: "Slot 1",
    status: "Packed",
    time: "09:15 AM",
    date: "Today, 20 Sep 2026",
    paymentMethod: "Credit Card",
    items: [
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 3, price: 240, total: 720 },
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 2, price: 245, total: 490 },
      { id: "KM004", name: "Soya Bean (1 kg)", quantity: 1, price: 180, total: 180 },
    ],
  },
  {
    id: "KM1022",
    customerId: "CUST-1003",
    name: "Sneha Iyer",
    amount: 540,
    store: "Store 1",
    slot: "Slot 2",
    status: "Out for Delivery",
    time: "08:50 AM",
    date: "Today, 20 Sep 2026",
    paymentMethod: "Cash on Delivery",
    items: [
      { id: "KM004", name: "Soya Bean (1 kg)", quantity: 2, price: 180, total: 360 },
      { id: "KM003", name: "Amul Butter (100 g)", quantity: 2, price: 55, total: 110 },
      { id: "KM006", name: "Maggi 2 Min Noodles (70 g)", quantity: 1, price: 70, total: 70 },
    ],
  },
  {
    id: "KM1021",
    customerId: "CUST-1004",
    name: "Amit Patil",
    amount: 2180,
    store: "Store 2",
    slot: "Slot 2",
    status: "Delivered",
    time: "07:20 AM",
    date: "Today, 20 Sep 2026",
    paymentMethod: "Net Banking",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 4, price: 290, total: 1160 },
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 3, price: 245, total: 735 },
      { id: "KM008", name: "Tata Salt (1 kg)", quantity: 10, price: 28, total: 280 },
    ],
  },
  {
    id: "KM1020",
    customerId: "CUST-1005",
    name: "Neha Kulkarni",
    amount: 730,
    store: "Store 1",
    slot: "Slot 1",
    status: "Cancelled",
    time: "05:12 AM",
    date: "Today, 20 Sep 2026",
    paymentMethod: "UPI / PhonePe",
    items: [
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 2, price: 240, total: 480 },
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 1, price: 245, total: 245 },
    ],
  },
];

export const ALL_ORDERS: Order[] = [
  ...mockOrders,
  {
    id: "KM1019",
    customerId: "CUST-1006",
    name: "Kiran Mehta",
    amount: 1150,
    store: "Store 1",
    slot: "Slot 2",
    status: "Delivered",
    time: "04:00 AM",
    date: "19 Sep 2026",
    paymentMethod: "UPI / Paytm",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 2, price: 290, total: 580 },
      { id: "KM003", name: "Amul Butter (100 g)", quantity: 4, price: 55, total: 220 },
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 1, price: 245, total: 245 },
    ],
  },
  {
    id: "KM1018",
    customerId: "CUST-1007",
    name: "Divya Rao",
    amount: 660,
    store: "Store 2",
    slot: "Slot 1",
    status: "Cancelled",
    time: "03:30 AM",
    date: "19 Sep 2026",
    paymentMethod: "Debit Card",
    items: [
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 2, price: 240, total: 480 },
      { id: "KM004", name: "Soya Bean (1 kg)", quantity: 1, price: 180, total: 180 },
    ],
  },
  {
    id: "KM1017",
    customerId: "CUST-1001",
    name: "Priya Sharma",
    amount: 2400,
    store: "Store 1",
    slot: "Slot 1",
    status: "Delivered",
    time: "02:45 AM",
    date: "18 Sep 2026",
    paymentMethod: "UPI / GooglePay",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 4, price: 290, total: 1160 },
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 3, price: 240, total: 720 },
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 2, price: 245, total: 490 },
    ],
  },
  {
    id: "KM1016",
    customerId: "CUST-1002",
    name: "Rahul Verma",
    amount: 310,
    store: "Store 2",
    slot: "Slot 2",
    status: "Packed",
    time: "02:10 AM",
    date: "18 Sep 2026",
    paymentMethod: "Credit Card",
    items: [
      { id: "KM002", name: "Colgate Toothpaste (200 g)", quantity: 2, price: 120, total: 240 },
      { id: "KM006", name: "Maggi 2 Min Noodles (70 g)", quantity: 1, price: 70, total: 70 },
    ],
  },
  {
    id: "KM1015",
    customerId: "CUST-1004",
    name: "Amit Patil",
    amount: 980,
    store: "Store 1",
    slot: "Slot 1",
    status: "Out for Delivery",
    time: "01:50 AM",
    date: "17 Sep 2026",
    paymentMethod: "Cash on Delivery",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 2, price: 290, total: 580 },
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 1, price: 240, total: 240 },
      { id: "KM006", name: "Maggi 2 Min Noodles (70 g)", quantity: 2, price: 70, total: 140 },
    ],
  },
  {
    id: "KM1014",
    customerId: "CUST-1008",
    name: "Ritu Gupta",
    amount: 1750,
    store: "Store 2",
    slot: "Slot 2",
    status: "Pending",
    time: "01:20 AM",
    date: "16 Sep 2026",
    paymentMethod: "Net Banking",
    items: [
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 4, price: 245, total: 980 },
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 2, price: 240, total: 480 },
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 1, price: 290, total: 290 },
    ],
  },
  {
    id: "KM1013",
    customerId: "CUST-1003",
    name: "Sneha Iyer",
    amount: 420,
    store: "Store 1",
    slot: "Slot 1",
    status: "Delivered",
    time: "12:55 AM",
    date: "15 Sep 2026",
    paymentMethod: "UPI / GooglePay",
    items: [
      { id: "KM006", name: "Maggi 2 Min Noodles (70 g)", quantity: 6, price: 70, total: 420 },
    ],
  },
  {
    id: "KM1012",
    customerId: "CUST-1005",
    name: "Neha Kulkarni",
    amount: 870,
    store: "Store 2",
    slot: "Slot 2",
    status: "Packed",
    time: "12:30 AM",
    date: "14 Sep 2026",
    paymentMethod: "Credit Card",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 3, price: 290, total: 870 },
    ],
  },
  {
    id: "KM1011",
    customerId: "CUST-1001",
    name: "Priya Sharma",
    amount: 3200,
    store: "Store 1",
    slot: "Slot 1",
    status: "Delivered",
    time: "Yesterday",
    date: "13 Sep 2026",
    paymentMethod: "UPI / PhonePe",
    items: [
      { id: "KM001", name: "Aashirvaad Atta (5 kg)", quantity: 5, price: 290, total: 1450 },
      { id: "KM005", name: "Surf Excel (1 kg)", quantity: 4, price: 240, total: 960 },
      { id: "KM007", name: "Dove Shampoo (340 ml)", quantity: 3, price: 245, total: 735 },
    ],
  },
  {
    id: "KM1010",
    customerId: "CUST-1006",
    name: "Kiran Mehta",
    amount: 540,
    store: "Store 2",
    slot: "Slot 2",
    status: "Cancelled",
    time: "Yesterday",
    date: "12 Sep 2026",
    paymentMethod: "Cash on Delivery",
    items: [
      { id: "KM004", name: "Soya Bean (1 kg)", quantity: 3, price: 180, total: 540 },
    ],
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "CUST-1001",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone: "+91 98201 45872",
    avatarColor: "#3B82F6",
    address: "Flat 402, Blossom Enclave, MG Road",
    city: "Mumbai",
    pincode: "400001",
    joinedDate: "14 Jan 2024",
    defaultStore: "Store 1",
    preferredSlot: "Slot 1",
    status: "Active",
    loyaltyTier: "Platinum",
    totalOrders: 18,
    totalSpent: 16480,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Priya Sharma" || o.customerId === "CUST-1001"),
  },
  {
    id: "CUST-1002",
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    phone: "+91 98765 12340",
    avatarColor: "#8B5CF6",
    address: "12A Green Avenue, Indiranagar",
    city: "Bengaluru",
    pincode: "560038",
    joinedDate: "02 Feb 2024",
    defaultStore: "Store 2",
    preferredSlot: "Slot 1",
    status: "Active",
    loyaltyTier: "Gold",
    totalOrders: 12,
    totalSpent: 11240,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Rahul Verma" || o.customerId === "CUST-1002"),
  },
  {
    id: "CUST-1003",
    name: "Sneha Iyer",
    email: "sneha.iyer@example.com",
    phone: "+91 97123 88452",
    avatarColor: "#EC4899",
    address: "Plot 89, Anna Salai, T Nagar",
    city: "Chennai",
    pincode: "600017",
    joinedDate: "20 Mar 2024",
    defaultStore: "Store 1",
    preferredSlot: "Slot 2",
    status: "Active",
    loyaltyTier: "Silver",
    totalOrders: 8,
    totalSpent: 4860,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Sneha Iyer" || o.customerId === "CUST-1003"),
  },
  {
    id: "CUST-1004",
    name: "Amit Patil",
    email: "amit.patil@example.com",
    phone: "+91 99345 67891",
    avatarColor: "#10B981",
    address: "Row House 7, Royal Palms, Kothrud",
    city: "Pune",
    pincode: "411038",
    joinedDate: "05 Nov 2023",
    defaultStore: "Store 2",
    preferredSlot: "Slot 2",
    status: "Active",
    loyaltyTier: "Platinum",
    totalOrders: 24,
    totalSpent: 28950,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Amit Patil" || o.customerId === "CUST-1004"),
  },
  {
    id: "CUST-1005",
    name: "Neha Kulkarni",
    email: "neha.k@example.com",
    phone: "+91 96541 23098",
    avatarColor: "#F59E0B",
    address: "B-201, Shanti Heights, Thane West",
    city: "Thane",
    pincode: "400601",
    joinedDate: "18 Dec 2023",
    defaultStore: "Store 1",
    preferredSlot: "Slot 1",
    status: "Active",
    loyaltyTier: "Silver",
    totalOrders: 6,
    totalSpent: 4120,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Neha Kulkarni" || o.customerId === "CUST-1005"),
  },
  {
    id: "CUST-1006",
    name: "Kiran Mehta",
    email: "kiran.mehta@example.com",
    phone: "+91 98450 67123",
    avatarColor: "#06B6D4",
    address: "Flat 14, Sunrise Towers, SG Highway",
    city: "Ahmedabad",
    pincode: "380015",
    joinedDate: "09 Jan 2024",
    defaultStore: "Store 1",
    preferredSlot: "Slot 2",
    status: "Active",
    loyaltyTier: "Bronze",
    totalOrders: 4,
    totalSpent: 2850,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Kiran Mehta" || o.customerId === "CUST-1006"),
  },
  {
    id: "CUST-1007",
    name: "Divya Rao",
    email: "divya.rao@example.com",
    phone: "+91 91234 56780",
    avatarColor: "#6366F1",
    address: "H-405, Orchid Residency, Jubilee Hills",
    city: "Hyderabad",
    pincode: "500033",
    joinedDate: "15 Apr 2024",
    defaultStore: "Store 2",
    preferredSlot: "Slot 1",
    status: "Inactive",
    loyaltyTier: "Bronze",
    totalOrders: 2,
    totalSpent: 1320,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Divya Rao" || o.customerId === "CUST-1007"),
  },
  {
    id: "CUST-1008",
    name: "Ritu Gupta",
    email: "ritu.gupta@example.com",
    phone: "+91 98112 34567",
    avatarColor: "#EF4444",
    address: "C-12, Green Park Main",
    city: "New Delhi",
    pincode: "110016",
    joinedDate: "28 Feb 2024",
    defaultStore: "Store 2",
    preferredSlot: "Slot 2",
    status: "Active",
    loyaltyTier: "Gold",
    totalOrders: 11,
    totalSpent: 14600,
    orderHistory: ALL_ORDERS.filter((o) => o.name === "Ritu Gupta" || o.customerId === "CUST-1008"),
  },
];

export const mockProducts = [
  {
    name: "Aashirvaad Atta",
    size: "5 kg",
    sku: "KM001",
    category: "Atta & Flour",
    store: "Store 1",
    stock: 120,
    price: 290,
    color: "#F97316",
    emoji: "🌾",
  },
  {
    name: "Colgate Toothpaste",
    size: "200 g",
    sku: "KM002",
    category: "Oral Care",
    store: "Store 1",
    stock: 85,
    price: 120,
    color: "#3B82F6",
    emoji: "🦷",
  },
  {
    name: "Amul Butter",
    size: "100 g",
    sku: "KM003",
    category: "Dairy",
    store: "Store 2",
    stock: 60,
    price: 55,
    color: "#FBBF24",
    emoji: "🧈",
  },
  {
    name: "Soya Bean",
    size: "1 kg",
    sku: "KM004",
    category: "Pulses",
    store: "Store 1",
    stock: 78,
    price: 180,
    color: "#84CC16",
    emoji: "🫘",
  },
  {
    name: "Surf Excel",
    size: "1 kg",
    sku: "KM005",
    category: "Cleaning",
    store: "Store 2",
    stock: 45,
    price: 240,
    color: "#6366F1",
    emoji: "🧺",
  },
  {
    name: "Maggi 2 Min Noodles",
    size: "70 g",
    sku: "KM006",
    category: "Snacks",
    store: "Store 1",
    stock: 150,
    price: 70,
    color: "#EF4444",
    emoji: "🍜",
  },
  {
    name: "Dove Shampoo",
    size: "340 ml",
    sku: "KM007",
    category: "Hair Care",
    store: "Store 2",
    stock: 95,
    price: 245,
    color: "#EC4899",
    emoji: "🧴",
  },
  {
    name: "Tata Salt",
    size: "1 kg",
    sku: "KM008",
    category: "Grocery",
    store: "Store 1",
    stock: 200,
    price: 28,
    color: "#64748B",
    emoji: "🧂",
  },
  {
    name: "Santoor Soap",
    size: "125 g",
    sku: "KM009",
    category: "Personal Care",
    store: "Store 2",
    stock: 0,
    price: 35,
    color: "#14B8A6",
    emoji: "🧼",
  },
];

export const mockTeam = [
  { name: "Ravi Kumar", email: "ravi@kmart.com", role: "Packer", store: "Store 1" },
  { name: "Suresh Nair", email: "suresh@kmart.com", role: "Packer", store: "Store 2" },
  { name: "Amit Shah", email: "amit@kmart.com", role: "Delivery", store: "Store 1" },
  { name: "Vikram Patil", email: "vikram@kmart.com", role: "Delivery", store: "Store 2" },
  { name: "Pooja Desai", email: "pooja@kmart.com", role: "Packer", store: "Store 1" },
  { name: "Imran Shaikh", email: "imran@kmart.com", role: "Delivery", store: "Store 2" },
];
